import Head from 'next/head'
import { useRouter } from 'next/navigation'
import { useEffect, useState } from 'react';
import { FaUserAlt } from "react-icons/fa";
import axios from 'axios';
import { FactComponent } from '@/components/FactComponent';


function Home() {
  const router = useRouter();

  const [data, setData] = useState([])

  useEffect(() => {
    const isUserLoggedIn = () => {
      const user = localStorage.getItem("user");
      if (!user) {
        router.replace('/login')
      }
    };
    const fetchData = async () => {
      const response = await axios.get('https://quiz-backend-service.onrender.com/fact')
      console.log(response)

      const sortedData = response.data.sort((a, b) => (b.likes.length - b.dislikes.length) - a.likes.length - a.dislikes.length);
      setData(sortedData);
    }
    fetchData()
    isUserLoggedIn();
  }, []);

  const handleLikeClick = (factData) => {
    console.log(`Liked by ${factData.userId}`);
  };

  const handleDislikeClick = (factData) => {
    console.log(`Disliked by ${factData.userId}`);
  };

  const goToMyFactPage = () => {
    router.push('/my-fact');
  };
  const about = () => {
    router.push('/about');
  }

  return (
    <>
      <Head>
        <title>Facts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/star.png " style={{ backgroundColor: "wheat" }} />
      </Head>
      <main>
        <div className='main-container'>
          <div className='navbar'>
            <h1 style={{ color: 'rgb(80, 113, 220)', fontSize: '48px', fontFamily: '  font-family: Impact, Haettenschweiler, "Arial Narrow Bold", sans-serif;' }}>Facts</h1>
            {/* <button id='selected'>Home</button> */}
            <button id='navbar-btn' onClick={() => goToMyFactPage()}>My Facts</button>
            <button style={{border:'none', backgroundColor:'#F1EAFF'}} onClick={() => about()}> <FaUserAlt color='#4a24a1' size={30}  /> </button>
          </div>
          <div className='facts'>
            {
              data.map((factData) => (
                <FactComponent key={factData.userId} setData={setData} factData={factData} data={data} onLikeClick={handleLikeClick(factData)} onDislikeClick={handleDislikeClick(factData)} />
              ))
            }
          </div>
        </div>
      </main >
    </>
  )
}

export default Home